### ISSUE TITLE
Upload multiple attachments

### ISSUE THREAD

**Issue by cpsmhammond** [Esri/workforce-scripts#10]
Hi,

is it possible to allow for uploading of multiple attachments with the create assignments from csv script?

**Comment by apulverizer** [comment]
Currently that is not possible. However, if you want to do that you could use some sort of delimiter in the attachments column to list multiple files. The script could then be modified to parse multiple attachments.

Something like the following, which uses a `;` to delimit the attachment file paths.

```
xField,yField,Type,Location,Dispatcher,Description,Priority,Work Order Id,Due Date,Attachment,Worker
-118.15,33.8,1,123 Street # 765,1,Test Description,4,1,4/28/2016 23:59:59,../sample_data/attachments/logo1.png,jane_doe_the_worker
-118.37,34.086,2,124 Street # 765,2,Test Description,3,2,4/29/2016 08:00:00,../sample_data/attachments/logo1.png;../sample_data/attachments/logo1.png;../sample_data/attachments/logo1.png3,jane_doe_the_worker
```

Then update the `get_assignments_from_csv` method accordingly.

**Comment by cpsmhammond** [comment]
great idea.  i got it modified and it is working perfectly using the extra delimiter in the attachment field.

thanks!
