### ISSUE TITLE
create_assignments_from_csv.py fails with import error

### ISSUE THREAD

**Issue by jmdye** [Esri/workforce-scripts#13]
create_assignments_from_csv imports the arrow module, which is not part of the standard distribution. Further, I tried to pip install arrow on both a Mac and Windows machine only to end up with pip failing with error message ```Could not find a version that satisfied the requirement arrow (from versions: ). No matching distribution found for arrow```

**Comment by apulverizer** [comment]
What version of Python are you using? Are you using conda, or any conda environments?

I can pip install arrow for Python 3.6 and Python 2.7 on my Mac.

**Comment by jmdye** [comment]
nvm. It installed fine a few minutes ago. Maybe it was an issue with pypi. sorry for the false alarm.
