### ISSUE TITLE
Add option to set Requests verify=False and disable insecure connection warnings

### ISSUE THREAD

**Issue by jmdye** [Esri/workforce-scripts#14]
I needed to modify the Workforce Helpers script as follows for use behind my corporate firewall:
```
import logging
import sys
import requests
# Disable warnings about Insecure Connections
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

def post(url, data=None, files=None):
    """
    Makes a POST request with the provided url and data
    :param url: (string) The url to post to
    :param data: (dictionary) The data (if any) to send
    :param files: (dictionary) The json data the holds the file info
    :return:
    """
    logging.getLogger().debug("Posting to: {}".format(url))
    # Added verify=False flag to prevent issues with SSL Verification errors
    response = requests.post(url, data, files=files, verify=False).json()
    logging.getLogger().debug(response)
    return response


def get(url, params=None):
    """
    Makes a GET request with the provided url and parameters
    :param url: (string) The url to get
    :param params: (dictionary) The parameters to submit
    :return:
    """
    params['f'] = 'json'
    logging.getLogger().debug("Getting: {}".format(url))
    # Added verify=False flag to prevent issues with SSL Verification errors
    response = requests.get(url, params, verify=False).json()
    logging.getLogger().debug(response)
    return response```

Might be better to add these as options to the Workforce Scripts

**Comment by apulverizer** [comment]
We're somewhat deprecating the standalone and arcrest scripts in favor of using the Python API For ArcGIS. 

In these scripts we default to ignore the certificates (which should resolve this): https://github.com/Esri/workforce-scripts/blob/master/arcgis_api_for_python/import_workers.py#L107

Perhaps we should default to verifying the certificate (for security) but provide a command-line option such as `--verify false` to disable it.

**Comment by jmdye** [comment]
I like that approach, can we add another to disable displaying SSL warnings (```urllib3.disable_warnings(InsecureRequestWarning```)? Those two kind of go hand-in-hand.

Perhaps something like ```--verify false --showSSLWarnings false```

Noticed you guys were deprecating the standalone scripts. Have to say I'm a little disappointed by that. I like the ability to just download the scripts and run them without the need to install the Python API or really anything else.

**Comment by apulverizer** [comment]
See PR #18 let me know what you think when you have a chance.
The Python API does not use requests or urllib3 we don't need `--showSSLWarnings` flag. 

And yeah I can see how having the standalone scripts is easier in some cases. It's just too much effort to maintain 2 or 3 versions of the scripts, and the Python API handles a lof the authentication issues and edge cases pretty well.

**Comment by apulverizer** [comment]
Merged PR.
