### ISSUE TITLE
Add Documentation on configuring HTTP Proxy for use with Requests

### ISSUE THREAD

**Issue by jmdye** [Esri/workforce-scripts#15]
Might be good to add information on configuring  HTTP and HTTPS Proxy environment variables. If someone is using these scripts behind a corporate firewall and trying to connect to AGOL, they're probably going to need to configure those environment variables.

**Comment by apulverizer** [comment]
This is a good idea. Do you have any examples you'd like to share? 

It looks like we just need to expose some command-line arguments for `poxy_host` and `poxy_port` as shown in the [Python API Doc](https://esri.github.io/arcgis-python-api/apidoc/html/arcgis.gis.toc.html#gis ).

**Comment by apulverizer** [comment]
After more thought, I don't think this is something we need to expose (we already have so many arguments). All of the new scripts are tightly integrated with the Python API which as documented how to configure a proxy, any script could be modified for a specific environment. Closing.
