### ISSUE TITLE
import_workers should throw an error if workerId is not valid

### ISSUE THREAD

**Issue by jmdye** [Esri/workforce-scripts#17]
Stumbled across this out of blatant user error. I had a typo in one of my workerId values in my CSV. I was able to execute ```import_workers.py``` against that CSV without any errors or warnings.

When I executed ```create_assignments_from_csv.py```, it threw an error when it tried to give assignments to the invalid workerId. 

Clearly there is some user error here but, when you're creating thousands of assignments, this is way too far down the line to find out you had an invalid workerId in your workersCSV. Imho, that should have been called out when you ran ```import_workers.py```, probably as a warning because if you dont fix it, you're going to run into issues when you try to create assignments .

It was only about 1,100 assignments for me but it still took a good 3-4 minutes before ```create_assignments_from_csv.py``` came across my invalid workerId and the error was raised.

**Comment by apulverizer** [comment]
Hi @jmdye,

Currently the import_workers script does detect invalid workers (usernames that are not in your org). It logs a warning message about this but does not stop the script. 

See lines: https://github.com/Esri/workforce-scripts/blob/master/arcgis_api_for_python/import_workers.py#L130 

Are you suggesting we first parse the csv and detect that all users are valid, then import all the workers. Currently, we go line by line which why we didn't want to raise an exception (which would lead to a partial import).

**Comment by jmdye** [comment]
Yes. My suggestion is to throw a fatal error and exit the script without importing any workers. Reason being that if your workers csv contains invalid workers, your assignments csv probably does as well. However, if your assignments csv contains an invalid worker for an assignment, then a fatal error is thrown there meaning you can get through a ton of assignments only to have to start over again if your assignments csv contained an invalid worker. That's painful when youre talking about hundreds or thousands of assignments.

**Comment by apulverizer** [comment]
See PR #18 let me know what you think when you have a chance.

**Comment by apulverizer** [comment]
Merged the PR. Closing.
