### ISSUE TITLE
Create Assignments

### ISSUE THREAD

**Issue by ghost** [Esri/workforce-scripts#2]
First I would like to say these scripts are great!!  Thanks you!

I would like to request to be able to designate the workerId in this script.  I have around 350 dumpsters assignments each day and need to assign them to the proper truck or worker.  This will prevent the dispatcher from having to manually assign them to the proper worker each day.

Thanks

Tred

**Comment by ghost** [comment]
I figured it out.  Since I did not need the workOrderID field I changed everything that had  workOrderID to workerId in the create assignments script.  Then I changed the Status to 1 on line 70.

**Comment by crai3162** [comment]
@tredriggs thanks for the comments, we're glad to hear the scripts are useful.

You've figured it out correctly; to assign work you need to set the WorkerID to the ObjectID from the Workers feature service and set the Status to 1.  You  should also set the assignedDate field.

We're working on updates to our doc that will also document this workflow; those should be online within the week.

**Comment by apulverizer** [comment]
Closing this as the issue has been resolved.
