### ISSUE TITLE
Matching Fields Assignments and Feature Layer

### ISSUE THREAD

**Issue by kcarrier** [Esri/workforce-scripts#20]
In a perfect world it would be great if there were matching fields between the assignments and feature layer that the field values would come over when the assignment is created as part of the GUI in workforce. If not a simple script to update matching fields between a feature layer and the corresponding assignment would be nice. I am wondering why there is not a relationship built between assignment and the feature layer(REL_GUID), this would make it even easier to update fields based on GUIDs. Is there a simple script to update the assignments layer from a feature layer?

**Comment by apulverizer** [comment]
Yeah I saw your comment on #8 

I think we can do something similar to https://github.com/Esri/workforce-scripts/blob/master/arcgis_api_for_python/copy_assignments_fs.py 

That example copies the assignments to a different feature layer (for archiving primarily). We could definitely go the other way around as well I think. In that example, a json file defines the field mappings between the two services: https://github.com/Esri/workforce-scripts/blob/master/sample_data/fieldMappings.json

**Comment by kcarrier** [comment]
Thank you for the prompt response. We re-read the other post and were not entirely sure it was the same thing so we started another issue in the hope we could better define the issue we are facing. We like the idea of archiving but in our case it just did not meet the business need. If you want a beta-tester just say the word. We really feel this functionality would be useful for a wide variety of users. Thanks again for looking into this.

**Comment by apulverizer** [comment]
Please check out the notebooks that will be demoed at UC 2018. I think [this one](https://github.com/Esri/workforce-scripts/blob/master/notebooks/UC_2018/integrating_workforce_demo_theatre/UC%202018%20-%203%20-%20Add%20Assignments%20From%20Existing%20Layer.ipynb) is pretty close to what you describe. It creates assignments from an existing layer.

Closing this.
