### ISSUE TITLE
Standalone Scripts - dispatcherId is not optional

### ISSUE THREAD

**Issue by jonathancgroves** [Esri/workforce-scripts#22]
The readme for the standalone create_assignments_from_csv.py script states:
> -dispatcherIdField <dispatcherIdField> - The name of the field in the CSV file that contains the dispatcher ID (Optional - if not provided, the authenticated user is used as the dispatcher)_

Omitting the integer dispatcherId value in the input csv file causes this error:

`[2018-02-19 08:56:08,973] [create_assignments_from_csv.py: 352 -  <module>()]
 [MainThread] [      root] [CRITICAL] Traceback (most recent call last): |   File "create_assignments_from_csv.py", line 348, in <module> |     main(args) |   File "create_assignments_from_csv.py", line 274, in main | 
    args.dateFormat, args.wkid, args.attachmentFileField, args.workerField, args.timezone) |   File "create_assignments_from_csv.py", line 84, in get_assignments_
from_csv |     if dispatcherIdField: new_assignment["data"]["attributes"]["dispatcherId"] = int(assignment[dispatcherIdField]) | ValueError: invalid literal for int() with base 10: '' | `

**Comment by apulverizer** [comment]
I can reproduce this. The parameter was meant to be optional when calling the script.
If `-dispatcherIdField` was supplied it was assumed that all assignments would have a dispatcherId in the CSV file. I see how that could be confusing based on the readme. 

I can add a check to ensure there is a dispatcherId value there, if not, then it will use the signed in user as the dispatcher. This change will only be done on the scripts that use the Python API for ArcGIS.

**Comment by apulverizer** [comment]
I pushed a fix for this (Python API only).

**Comment by jonathancgroves** [comment]
Noted - thanks. See my other comment re your dropping the standalone scripts, but this particular issue is clearly now closed. Thanks for your help.
