### ISSUE TITLE
Standalone Scripts - create_assignments_from_csv.py - OBJECTID references fail

### ISSUE THREAD

**Issue by jonathancgroves** [Esri/workforce-scripts#24]
Whilst it appears that `objectid` fields are aliased as `OBJECTID` in the feature layer (although navigating this is somewhat challenging!) I have been unable to get the above Python script to run unless I replace all instances of `OBJECTID` with `objectid`.
This seemed to work fine with AGOL-based Workforce, I believe it may be a change introduced for Enterprise Workforce.
Hope this helps.

Jonathan

**Comment by apulverizer** [comment]
Same issue as as https://github.com/Esri/workforce-scripts/issues/23

**Comment by jonathancgroves** [comment]
Noted - I'm closing as this adds no value., Thanks.
