### ISSUE TITLE
ASSIGNMENT MONITOR

### ISSUE THREAD

**Issue by Murkor** [Esri/workforce-scripts#26]
WHERE I CAN GET AN CONFIG.INI FILE FOR THE ASSIGNMENT_MONITOR PROGRAM

**Comment by apulverizer** [comment]
https://github.com/Esri/workforce-scripts/blob/master/arcgis_api_for_python/assignment_monitor/config.ini

Add your info to it and it should "just work".

**Comment by Murkor** [comment]
Thanks I tried with 
# workforce/agol project id
[WORKFORCE]
PROJECT = 80a36dedd957479ab81c521f60394589

# slack webhook
[SLACK]
WEBHOOK = https://hooks.slack.com/services/esripro_hook

# AGOL auth info
[AGOL]
ORG = https://esripro.maps.arcgis.com
USERNAME = my_username
PASSWORD = my_password

# log file
[LOG]
LOGFILE = log.txt

[DB]
DATABASE = assignments.db

And start working properly , no error messages

**Comment by Murkor** [comment]
ah ... delete_assignments_type.py is missing

**Comment by apulverizer** [comment]
Yeah it was a typo in the readme, just fixed it.

**Comment by Murkor** [comment]
thanks again...
