### ISSUE TITLE
after installing get "ImportError: no module named arrow"

### ISSUE THREAD

**Issue by billwie** [Esri/workforce-scripts#28]
I've followed the directions to install the tools using pip and when i attempt to run "create_assignments_from_csv" i receive "ImportError: no module named arrow". ArcGIS Pro 2.1.3 with ArcGIS Rest API installed.

**Comment by apulverizer** [comment]
@billwie When you ran `pip install -r requirement.txt` did you have the correct Python Environment activated? 

Either way, you should be able to run `pip install arrow` to install the arrow dependency.
I cannot reproduce using a fresh conda environment.

**Comment by billwie** [comment]
Definitely running the ArcGIS Pro Python environment. I used the start menu link for "python command prompt" installed with Pro and the command line is prefixed with "(arcgispro-py3)"

Running pip install arrow resulted in three lines which read "Requirement Already satisfied"

I tried uninstalling 'arrow' and re-installing it with no change in my script. Next I'll try this on another machine to see if it machine specific.

FYI clip from command line with certain parts redacted to protect the guilty:

(arcgispro-py3) C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3>pip in
stall arrow
Requirement already satisfied: arrow in c:\program files\arcgis\pro\bin\python\e
nvs\arcgispro-py3\lib\site-packages
Requirement already satisfied: python-dateutil in c:\program files\arcgis\pro\bi
n\python\envs\arcgispro-py3\lib\site-packages (from arrow)
Requirement already satisfied: six>=1.5 in c:\program files\arcgis\pro\bin\pytho
n\envs\arcgispro-py3\lib\site-packages (from python-dateutil->arrow)
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.

(arcgispro-py3) C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3>C:\Dat
a\FaresWorkforce\workforce-scripts-master\scripts\create_assignments_from_csv.py
 -csv-file "C:\Data\FaresWorkforce\Test1.csv" -u XXXX -p XXXX -org "https:/
/XXXX/portal" -project-id "XXXX" -x-field "
xField" -y-field "yField" -assignment-type-field "Type" -location-field "Locatio
n" -description-field "Description" -work-order-id-field "WorkOrderId" -wkid 432
6 -log-file "C:\Data\FaresWorkforce\log.txt" -worker-field "Worker" -timezone "U
S/Central"
Traceback (most recent call last):
  File "C:\Data\FaresWorkforce\workforce-scripts-master\scripts\create_assignmen
ts_from_csv.py", line 32, in <module>
    import arrow
ImportError: No module named arrow

**Comment by apulverizer** [comment]
I can't reproduce your issue.

Can you try running `python C:\Dat
a\FaresWorkforce\workforce-scripts-master\scripts\create_assignments_from_csv.py <all the other params>` in the `(arcgispro-py3)` environment. 

You are just directly running the script. I wonder if you have Windows configured to run `.py` files with a specific python interpreter, which then ignores the interpreter that is activated.

**Comment by billwie** [comment]
Thanks this worked. the issue was that i was not including the "python" at the beginning and the system was using the wrong interpreter.
