### ISSUE TITLE
Adding Carriage Returns to Description Field?

### ISSUE THREAD

**Issue by billwie** [Esri/workforce-scripts#30]
Is anyone aware of a way to add carriage returns to a description field from the CSV using "Create Assignments From CSV"? using \n in the CSV does not work. I'm tempted to try closing the string by placing a double quote but i'm not sure how the python interpreter would read that.

**Comment by billwie** [comment]
Yeah should have known that will not work. the string is treated as an object and not parsed as code itself and rightly so.

**Comment by apulverizer** [comment]
If you have a multi-line CSV field, the default Python parsing seems to pick that up.

https://stackoverflow.com/questions/566052/can-you-encode-cr-lf-in-into-csv-files

test.csv
```
"abc
def",abcdef,abcdef
```

test.py
```python
import csv
with open('test.csv') as f:
    csvread = csv.reader(f)
    for row in csvread:
        print(row)
print(row[0])
```

Output:
```
['abc\ndef', 'abcdef', 'abcdef']
abc
def
```

I am closing this issue as I think it address your question. If not, feel free to re-open.
