### ISSUE TITLE
-attachmentFileField

### ISSUE THREAD

**Issue by kawikakanaka** [Esri/workforce-scripts#33]
**Describe the bug**
the default python example for "create_assignments_from_csv.py" has "-attachmentFileField" which should be formatted as "-attachment-file-field"

**To Reproduce**
1. 
2.
3.
4.

**Expected behavior**

**Desktop (please complete the following information):**
 - Python Version:

**Additional context**

**Comment by apulverizer** [comment]
Thanks for reporting this, I just updated the readme to fix that line.

**Comment by kawikakanaka** [comment]
Cool thanks!  I need some help with running the scripts...is this the place to ask for that?

**Comment by apulverizer** [comment]
If you run into an issue with a specific script then feel free to open an issue in this repo. 
If you want general advice about scripting, you're probably better off posting on Geonet  under the Workforce for ArcGiS section or ArcGIS API for Python section.

You can also just email me if you want: apulver@esri.com
