### ISSUE TITLE
Authentication fails when using Enterprise login

### ISSUE THREAD

**Issue by kangh** [Esri/workforce-scripts#38]
**Describe the bug**
Authentication fails when using Enterprise account. The Enterprise account is added as a dispatcher so the account has permissions on the project. It works if an ArcGIS Online login is used instead. I have tried the Enterprise email address and username for -u argument and it still fails. I don't see any additional arguments for enterprise account.

  python C:\temp\workforce-scripts-master\scripts\export_assignments_to_csv.py 
 -csv-file "C:\temp\workforce-scripts-master\sample_data\export_assignments.csv" 
 -u <enterprise email/enterprise username> 
 -p <my password>
 -org "https://xxxxx.maps.arcgis.com" 
 -project-id "the project id" 
 -log-file "C:\temp\workforce-scripts-master\sample_data\logExportAssignments.txt" 
 -where "status=1" 
 -date-format "%m/%d/%Y %H:%M:%S" 
 -timezone "US/Pacific"

**To Reproduce**
1. I am running the script from the Python Command Prompt
2. I get an error - Unable to generate token. Invalid username or password.

**Expected behavior**
Be able to use a dispatcher enterprise account to export/create assignments

**Desktop (please complete the following information):**
OS: Windows 10
Python Version: 3.x

**Additional context**

**Comment by apulverizer** [comment]
@kangh when you sign into ArcGIS Online, are you using SAML through some other identify provider?

**Comment by kangh** [comment]
That is correct.

**Comment by apulverizer** [comment]
These scripts will not support SAML out of the box

You'll have to do more work to authenticate with SAML. There is some information here: https://developers.arcgis.com/python/guide/working-with-different-authentication-schemes/#User-authentication-with-OAuth-2.0

**Comment by kangh** [comment]
Thank you. I will take a look at the resource you provided.
