### ISSUE TITLE
Copy assignments does not copy feature service attachments

### ISSUE THREAD

**Issue by AviCueva** [Esri/workforce-scripts#41]
**Is your feature request related to a problem? Please describe.**
When utilizing the copy_assignments_to_fs.py script attachments are not copied to the target feature service.

**Describe the solution you'd like**
Attachments if present should be copied over.

I was trying to utilize this script for archival purposes, without attachments copying over, I am not able to utilize this script.

**Comment by apulverizer** [comment]
@AviCueva Can you try this branch? 

~https://github.com/Esri/workforce-scripts/tree/feature/export-attachments~

**Comment by apulverizer** [comment]
@AviCueva the script has been updated (in master branch), please try the latest.

**Comment by AviCueva** [comment]
@apulverizer Thank you.  I can confirm the script works properly.

Let me know next time you're in Redlands, would love to buy you a beer!
