### ISSUE TITLE
Will assign assignments based on point features

### ISSUE THREAD

**Issue by robeisenrich** [Esri/workforce-scripts#46]
**Is your feature request related to a problem? Please describe.**
The script option for assigning assignments based on existing feature services will only work if that feature service is a point feature.

**Describe the solution you'd like**
I would like to be able to assign assignments to line and polygon features. For my use case, I want our field personnel to investigate all water utility assess along a length of water main. Doing this reduces the effort of assigning work assignments to all water assets.

**Describe alternatives you've considered**
The work around I am currently using incorporates the "points along a line" tool to generate mid points for each line feature. I than use this feature service to create the workforce assignments. 
**Additional context**
The above work around is not ideal as it creates a additional update step for my team as we have to re-create the point features any time our line feature is updated.

**Comment by niravi** [comment]
Thanks for your feedback @robeisenrich - currently assignment geometry in Workforce contains point geometry, so making an assignment that has a line or a polygon would be a pretty large schema change. This is feedback we've received before and is not currently in the product plan. I think your workaround makes a lot of sense - how often is the line updated? We could perhaps look at optimizing your update step.

**Comment by niravi** [comment]
Closing for now
