### ISSUE TITLE
Create assignments - workOrderIdField & locationField

### ISSUE THREAD

**Issue by nart-t** [Esri/workforce-scripts#5]
Scripts work great and are very useful, but I'm a bit unclear on two things on the assignment creation script:

1.  It seems the script tries to enforce the workOrderIdField being an integer. Why is that? The Assignments schema in a Workforce project seems to have the workOrderId field as text. This is actually a bit of a blocker since those IDs might originate from other systems, and in my case they are not just numbers.
![workforce_servicesschema](https://cloud.githubusercontent.com/assets/5878887/21222242/dfc6fd84-c2b8-11e6-89d5-16311c4a435f.PNG)

UPDATE: Modified line 81 in the script, by removing the int() around the workOrderIdField and it now imports the ID fields as is. Still would like to know why it was enforced?

2. Why is the locationField required? Shouldn't it be enough having X/Y coordinates to establish it? If X/Y is all you have you would potentially need to reverse geocode to get some sort of textual location info

**Comment by ming800** [comment]
Same issue here, my workOrderId is a string data.  Thanks for the tip.

In addition, the dispatcherId should be a integer instead of string. After adding the int() in line 78, it work fine now.

Thanks for the great tool!

Ming

**Comment by ming800** [comment]
Why is the locationField required? 
Location field is very useful for many situations.  The XY or Lat/Lon are just numbers. It is difficult for none GIS/geographer person to reference the numbers to a location in real world. We use the tool for water utility work orders. The location field is used to store a FacilityID, such as ID/Ma,e for a pump station or valve, an accountNumber for meter repair, or a address for new service installation.

Ming

**Comment by ming800** [comment]
After reading the codes, realize that the dispatcherID is intended for a string name of the dispatcher. The code will looking for the oid for the matching name. 

Ming

**Comment by crai3162** [comment]
@nart-t thanks for your comments on the scripts:
1. this was an oversight in the script; WorkOrderID can be either int or string; we'll get this clarified.
2. @ming800 provided a great reply on why we require locationField to be set; in the case where you only need to use X/Y coordinates. you can enter those as the locationField, that is what the Workforce web app does when the reverse geocode does not return an address.

@ming800 thanks for the comment on the dispatcherID, will also make sure we update the scripts for this as well.

**Comment by apulverizer** [comment]
The scripts have been updated so that it does not cast workOrderId to an integer and so that it does cast dispatcherId to integer. 

I'm closing this as it should be solved, but feel free to re-open if these changes did not address your issue.
