### ISSUE TITLE
Create Assignment from Existing Feature Service

### ISSUE THREAD

**Issue by brianjbaldwin** [Esri/workforce-scripts#8]
I am looking for a script to take an existing FS and then map the fields to an existing Assignments FS to generate new assignments.  I assumed the copy_assignments_fs was exactly this, but I had the logic backwards.

This would be really useful in the gas space, where users may have overlapping areas that need to be managed by different types of assignments.  While the batch assignment tool works great for many features of one type in a geography, it becomes difficult to create assignments of many different overlapping types.

**Comment by jswagger** [comment]
This would be extremely helpful for my workflows as well. Right now I have to run the create_assignments_from_csv.py, and it takes forever to process (5,000 assignments). Being able to publish a feature service, then point Workforce at that service, or copy records over to the assignments service would be great.

**Comment by kcarrier** [comment]
Add City of Hamilton, OH to the list. We would like to be able to pass multiple fields from a feature layer to the assignments layer and then from the assignments layer to Survey123. This would essentially give us a trail back to the original feature allowing us to generate comprehensive reports and linking all the data together.

**Comment by apulverizer** [comment]
This will be demoed at the 2018 UC in the Integrating Workforce For ArcGIS with Other Systems (Wednesday afternoon). The notebook that will be used is hosted [here](https://github.com/Esri/workforce-scripts/blob/master/notebooks/UC_2018/integrating_workforce_demo_theatre/UC%202018%20-%203%20-%20Add%20Assignments%20From%20Existing%20Layer.ipynb)

Closing this.
