### ISSUE TITLE
Do scripts work with New WorkForce?

### ISSUE THREAD

**Issue by bkaplan1** [Esri/workforce-scripts#80]
**Describe the bug**
I created a new WorkForce project at workforce.arcgis.com.

From within ArcGIS Online, using Notebooks.....
In script 1, I connect to the organization using the same account used to create a WorkForce Project.

The following code does not list any New WorkForce projects.  I do see classic WorkForce Projects
item = gis.content.search("type:'Workforce Project' '*'")

I also try AGO assistant.  I grab the project id code of the New WorkForce project and use it to search AGO assistant.  The only items returned are the Feature Layer for the New Workforce Project.

**Comment by apulverizer** [comment]
@bkaplan1 for classic projects, you use the item id of Workforce Project. For offline enabled projects you need the feature service item id. To find offline enabled projects, use a search query like `type:"Feature Service" AND typekeywords:"Workforce Project"`

**Comment by bkaplan1** [comment]
@Arron Thank you for your reply.    I tried type:"Feature Service" AND typekeywords:"Workforce Project" in AGO Assistant and the response is only Feature Service (Hosted).

As I wasn't sure where I should apply this query, I also looked at it using it in via the python API inside AGO notebook but the search object

item = gis.content.search(query= "owner:" + gis.users.me.username, item_type='Feature Service')

doesn't have a typekeywords argument and the syntax is different.

I feel like I'm not understanding something.
________________________________

**Comment by apulverizer** [comment]
@bkaplan1 you can just directly use the parameters in the query parameter, the method parameters are just helpers. For example:

```python
items = gis.content.search(f'type:"Feature Service" AND typekeywords:"Workforce Project" AND owner:{gis.users.me.username}')
```

Should return all of the offline enabled workforce project items.

**Comment by bkaplan1** [comment]
Thanks for you example.  I’m still at a roadblock.

The types of items I get returned from
items = gis.content.search(f'type:"Feature Service" AND typekeywords:"Workforce Project" AND owner:{gis.users.me.username}')

are Feature Layer Collection

Can I query a Feature Layer Collection for


  *   Worker and Dispatchers
  *   Assignments
  *   Integrations
As shown here
https://developers.arcgis.com/python/guide/managing-workforce-projects/


A starting point on this web page, I’m particularly having trouble with is straight from the webpage

# This instantiates a project that previously existed for an offline-enabled project.
fs_item_id = "04b66b18d43a1804b66b1a188c2e"
fs_item = gis.content.get(fs_item_id)
offline_project = arcgis.apps.workforce.Project(fs_item)



In my case
items = gis.content.search(f'type:"Feature Service" AND typekeywords:"Workforce Project" AND owner:{gis.users.me.username}')

Is items[1] comparable to fs_item?  Or how do I get the feature service ID?

If so,   offline_project = arcgis.apps.workforce.Project(item[1])   (is the webpage wrong with using arcgis.apps?)

Returns
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-46-73248d2d1880> in <module>
----> 1 project = arcgis.apps.workforce.Project(item=item)

NameError: name 'arcgis' is not defined




So I try this.
offline_project = workforce.Project(item[1])

and get this.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-48-96f72f64f984> in <module>
----> 1 project = workforce.Project(item=items[1])

/opt/conda/lib/python3.6/site-packages/arcgis/apps/workforce/project.py in __init__(self, item)
     43         self._item = item
     44         self._item_data = item.get_data()
---> 45         self._assignment_schema = AssignmentSchema(self.assignments_layer)
     46         self._track_schema = TrackSchema(self.tracks_layer)
     47         self._worker_schema = WorkerSchema(self.workers_layer)

/opt/conda/lib/python3.6/site-packages/arcgis/_impl/common/_utils.py in _lazy_property(self)
    156     def _lazy_property(self):
    157         if not hasattr(self, attr_name):
--> 158             setattr(self, attr_name, fn(self))
    159         return getattr(self, attr_name)
    160     return _lazy_property

/opt/conda/lib/python3.6/site-packages/arcgis/apps/workforce/project.py in assignments_layer(self)
    231     def assignments_layer(self):
    232         """The assignments :class:`~arcgis.features.FeatureLayer`"""
--> 233         return FeatureLayer(self.assignments_layer_url, self.gis)
    234
    235     @_lazy_property

/opt/conda/lib/python3.6/site-packages/arcgis/apps/workforce/project.py in assignments_layer_url(self)
    181     def assignments_layer_url(self):
    182         """The assignments feature layer url"""
--> 183         return self._item_data['assignments']['url']
    184
    185     @_lazy_property

KeyError: 'assignments'





Brian Kaplan

Environmental Health Scientist/Geographer
Geospatial Research, Analysis, and Services Program (GRASP)
bkaplan@cdc.gov<mailto:bkaplan@cdc.gov> | Phone: 770.488.3823 | Cell: 404.316.9154 | Fax: 404.488.4566

**Comment by apulverizer** [comment]
@bkaplan1 

> Is items[1] comparable to fs_item?  Or how do I get the feature service ID?

> offline_project = workforce.Project(item[1])

This should work, can you check the version of the api you are using:
```python
import arcgis
print(arcgis.__version__)
```

**Comment by bkaplan1** [comment]
I’m using ArcGIS Online notebooks which identify as version 1.8.1.


Brian Kaplan

Environmental Health Scientist/Geographer
Geospatial Research, Analysis, and Services Program (GRASP)
bkaplan@cdc.gov<mailto:bkaplan@cdc.gov> | Phone: 770.488.3823 | Cell: 404.316.9154 | Fax: 404.488.4566

**Comment by apulverizer** [comment]
Okay, you need to update the arcgis library to 1.8.3 pre-release when running in the hosted notebook. 
An example is hosted here (notice the top commented out block): https://www.arcgis.com/home/item.html?id=f0488d21719f4decafe317670a56204a#preview

There a multiple examples hosted: 
https://www.arcgis.com/home/group.html?id=c1695c0c2f9945a8a7fee7dd106c74ae#overview

**Comment by bkaplan1** [comment]
Thanks.  My bad.   I saw some reference to 1.8.3 earlier but assumed that the ArcGIS Online Notebooks were using an appropriate version.

So I got 1.8.3 running on my local machine.  Thank you very much.

However, I’m having another problem I hope you can help me with.

When logging in with a OAuth2 Approval method and running

offline_project = arcgis.apps.workforce.Project(items[1])

I get this exception:

Exception: Token Required
Token Required
(Error Code: 499)

I do get a correct response when I enter
gis.properties.user.username


If I use a Named User Account I do not get this error.  It is better I use the OAuth2 method.

I can generate a token using
token = gis._con.token

How would I apply a token when I run the workforce.Project command?

Thanks

**Comment by apulverizer** [comment]
@bkaplan1 I dug into this and believe it's a bug in the underlying ArcGIS API for Python. I've opened an internal bug for it.

**Comment by apulverizer** [comment]
@bkaplan1 the authentication issue using OAuth should be resolved in the next update of the Python API. The `workforce.Project` uses the items gis which should already be using the token. The bug was that some POST requests (when using the OAuth workflow) were not correctly setting the token in the header. I don't think there is any workaround.

I'm closing this since the original issue was resolved. Feel free to re-open or create a new issue if you run into more problems.
