### ISSUE TITLE
Cannot execute create_assignments_from_csv due to Type error

### ISSUE THREAD

**Issue by LPowell-GIS** [Esri/workforce-scripts#83]
**Describe the bug**
I am attempting to execute the above script but it fails on the Assignment Type field as follows:

Traceback (most recent call last): |   File "create_assignments_from_csv.py", line 233, in <module> |     main(args) |   File "create_assignments_from_csv.py", line 119, in main |     assignment_type=assignment_type_dict[assignment[args.assignment_type_field]], | KeyError: 'Type' |

**To Reproduce**
Execute and Params as follows:
python create_assignments_from_csv.py -csv-file "..KSN\KSN_Script_Batch2.csv" -u ******* -p ******* -org "*********" -project-id "**********" -assignment-type-field "Type" -location-field "Location" -description-field "Description" -priority-field "Priority" -work-order-id-field "Work Order Id" -due-date-field "Due Date" -attachment-file-field "Attachment" -log-file "..\log.txt" -worker-field "Worker" -timezone "US/Pacific"

CSV as follows:
Type,Location,Dispatcher,Description,Priority,Work Order Id,Due Date,Worker,Attachment
BEF,135 Ballymena Road Doagh Ballyclare BT39 0TN,,Test,high,1,18/12/2020,Lpowell,
BEF,18 High St Holywood BT18 9AD,,Test,low,2,19/12/2020,Lpowell,
BEF,Block B Ashtown Gate Navan Rd Ashtown Dublin 15 D15 NP9Y,,Test,med,3,20/12/2020,Lpowell,
BEF,234 Ballymena Rd BT39 0TP,,Test,none,4,21/12/2020,Lpowell,

**Expected behavior**
Batch upload of assignments to Workforce using Geocoder

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version: 3.7

**Additional context**
Download and created workforce-scripts env as per [link](https://www.esri.com/arcgis-blog/products/workforce/field-mobility/monitor-assignment-status-in-arcgis-dashboards-using-a-joined-workforce-layer/).

**Comment by apulverizer** [comment]
Hi @LPowell-GIS 

The error seems to indicate that your CSV file does not have a `Type` column. The script is case and white-space sensitive for the column names. Can you check your file?

**Comment by LPowell-GIS** [comment]
Hey Aaron,

Thanks for getting back to me.

As per initial post, Type is first column. I'm skipping X/Y to use the Geocoding capability.

Lee

**Comment by apulverizer** [comment]
@LPowell-GIS I can't reproduce the issue. I copied the text you posted above and just changed the worker name:

[test.csv.zip](https://github.com/Esri/workforce-scripts/files/5716656/test.csv.zip)

It worked fine for me. Can you attach the actual CSV file?

**Comment by LPowell-GIS** [comment]
Hey Aaron,

Your csv works, despite looking no different from mine. Strange.

Thanks for your help and the great script.

Lee
