### ISSUE TITLE
assignementread field doesn't exist

### ISSUE THREAD

**Issue by kawikakanaka** [Esri/workforce-scripts#88]
I received the following error when running the migrate_assignments.py script:

"... Exception: The submitted field 'assignmentread' does not exist in the table 'db_ugnsv.hsu_ao66g.workforce_b_cc64467abc4e3b9fd14283_assignments'. | (Error Code: 500) |"

My classic project had that field, as an integer field, so I simply added it to the V2 project and the script ran successfully.  I didn't see this issue mentioned anywhere so I thought I'd post it.

**Comment by niravi** [comment]
Thanks for reporting @kawikakanaka - I have pushed a fix to the migration scripts
